before_script:
  - npm install --legacy-peer-deps

publish:
  image: node:latest
  stage: deploy
  script:
    # Extract a few values from package.json
    - NPM_PACKAGE_NAME=$(node -p "require('./package.json').name")
    - NPM_PACKAGE_VERSION=$(node -p "require('./package.json').version")

    - echo "Version ${NPM_PACKAGE_VERSION} of ${NPM_PACKAGE_NAME}"
    - npm run semantic-release
